### ISSUE TITLE
'NoneType' object has no attribute 'refresh_view' Python 3.9, Windows

### ISSUE THREAD

**Issue by b1scoito** [mahaloz/DAILA#10]
OS: Windows
IDA Pro version: 7.6

The right-click context menu doesn't appear to be updating:
![image](https://user-images.githubusercontent.com/17802984/210166502-7965f3b9-3984-4bb4-b8ac-a2e0a05e3a12.png)

Setting an API key or using "Identify the source of the current function" triggers the following error:

```py
Traceback (most recent call last):
  File "ida/plugins/daila_ida.py", line 139, in activate
    dec_view.refresh_view(False)
AttributeError: 'NoneType' object has no attribute 'refresh_view'
```

**Comment by mahaloz** [comment]
Would you be able to give any other information on how you triggered this? Are you on the latest commit? When you first launch, and open the context menu, do you see DAILA? since in the screenshot above I see it not listed in the context menu. If this is the case that it does not appear on first launch, try re-installing DAILA with `pip3 install -e .`

**Comment by b1scoito** [comment]
I followed the Installation guide on README:
```bash
pip3 install -e . && daila --install 
```
Tried re-installing but to no success, I'm on latest commit, and I do not see DAILA in the context menu (right-click) as soon as I launch.

**Comment by b1scoito** [comment]
Fixed it by downgrading my Python version to 3.9 from 3.10.1, switched using the binary `idapyswitch.exe`.

One thing I forgot to mention before is, on either Python version I get the following error:
```py
Traceback (most recent call last):
  File "C:\Users\biscoito\AppData\Local\Programs\Python\Python39\Scripts\daila-script.py", line 33, in <module>
    sys.exit(load_entry_point('DAILA', 'console_scripts', 'daila')())
  File "C:\Users\biscoito\AppData\Local\Programs\Python\Python39\Scripts\daila-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\biscoito\desktop\coisas\daila\daila\__main__.py", line 3, in <module>
    from .installer import DAILAInstaller
  File "c:\users\biscoito\desktop\coisas\daila\daila\installer.py", line 5, in <module>
    from binsync.installer import Installer
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\binsync\installer.py", line 2, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```
That I fixed by installing the Python 3 version of readline:
```bash
pip install pyreadline3
```

**Comment by mahaloz** [comment]
@b1scoito Ah thanks... that is strange, since 3.10 is the version I test on for Ubuntu... I'll add a note about this in the README for Windows use. I also did not realize `readline` did not work on Windows, and that you needed to install the windows version for it to work.

**Comment by mahaloz** [comment]
> That I fixed by installing the Python 3 version of deadline
Alright, you should no longer need to install anything as a workaround. `BinSync`, the place I get the installer from, is now updated to use `prompt_toolkit`, which is supported on Windows.

**Comment by mahaloz** [comment]
Closing this since it appears to be fixed now. Repopen otherwise.
