### ISSUE TITLE
Fail on ghidra identify function c++ decompile

### ISSUE THREAD

**Issue by soez** [mahaloz/DAILA#3]
daila_ghidra.py> Running...
[+] Starting identification of function FUN_00102c54
Traceback (most recent call last):
  File "/home/noname/ghidra_scripts/daila_ghidra.py", line 75, in <module>
    identify_function()
  File "/home/noname/ghidra_scripts/daila_ghidra.py", line 69, in identify_function
    request_identification()
  File "/home/noname/ghidra_scripts/daila_ghidra.py", line 54, in request_identification
    resp = server.identify_function(decomp)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1574, in _ServerProxy__request
    response = self.__transport.request(
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<class 'TypeError'>:exceptions must derive from BaseException">
daila_ghidra.py> Finished!

**Comment by mahaloz** [comment]
@soez could you try again on master? I've updated the exception raise to be more descriptive. You should still be seeing an exception, but at least now you will know why. It was an `openai` exception, so it's likely to do with either your key or your rate-limit.

**Comment by mahaloz** [comment]
@soez oh interesting... I see. Try pull again, I've changed the exception throwing to only use Python2 exceptions from now on when Ghidra is connected.

**Comment by soez** [comment]
mm it yet seems the same :(

```
daila_ghidra.py> Running...
[+] Starting identification of function FUN_00102c54
Traceback (most recent call last):
  File "/home/noname/ghidra_scripts/daila_ghidra.py", line 75, in <module>
    identify_function()
  File "/home/noname/ghidra_scripts/daila_ghidra.py", line 69, in identify_function
    request_identification()
  File "/home/noname/ghidra_scripts/daila_ghidra.py", line 54, in request_identification
    resp = server.identify_function(decomp)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1574, in _ServerProxy__request
    response = self.__transport.request(
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/home/noname/ghidra_10.1.5/Ghidra/Features/Python/data/jython-2.7.2/Lib/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<class 'TypeError'>:exceptions must derive from BaseException">
daila_ghidra.py> Finished!
```

**Comment by mahaloz** [comment]
Would you be able to confirm you installed it with `pip3 install -e .`?

**Comment by soez** [comment]
Yes, i deleted the folder DAILA and i cloned a new and after i installed with that

**Comment by mahaloz** [comment]
@soez hmmm alright this is a troubling problem. I've added one more commit, try installing one more time. If that does not work, it will be hard to continue to debug. It's just a guess, but it could be because you are on 10.1.5. I tested for 10.2. 

If you run on the latest now, the exception should at least look different (line numbers), which we can use to confirm the install was correct and has changed.

**Comment by soez** [comment]
Sorry for writing late

```
daila_ghidra.py> Running...
[+] Starting identification of function FUN_00102c54
('Exception occurred', <Fault 1: "<class 'TypeError'>:BaseException() argument after ** must be a mapping, not tuple">)
[+] Finished
daila_ghidra.py> Finished!
```

**Comment by mahaloz** [comment]
Got it; it looks like another error handler error. Since it could be at least 2 more commits back and forth for this, I've made a new branch: `fix/py_errors`. If you could switch to this branch for testing that would be great. 

You should only need to do a `git pull && git checkout fix/py_errors`, if you installed with `pip3 install -e .`. You don't need to re-clone each time and pip install.

**Comment by soez** [comment]
I knew do not worry :)

```
daila_ghidra.py> Running...
[+] Starting identification of function FUN_00102c54
[+] Finished
daila_ghidra.py> Finished!
```

**Comment by mahaloz** [comment]
@soez so you don't get any error printout now? Did you get comments in Ghidra for that function?

**Comment by soez** [comment]
I do not get comments in Ghidra, not :( without errors on print yes

**Comment by mahaloz** [comment]
@soez I see. Ok I've pushed another commit to the same branch to make a better error message. I think your system is blocking the Py3 server from starting. 

Also, if you want to fix this in a less async manner, you can join a discord I run: https://discord.gg/gCKAdrSR (BinSync), I can debug with you much faster there.

**Comment by mahaloz** [comment]
Since we've established over Discord that the bug is now in usage (key error), I'm going to close this issue and merge the working branch we've been using @soez. Feel free to open another issue if you find the network issue to be a real problem.
