### ISSUE TITLE
No context menu in Ghidra

### ISSUE THREAD

**Issue by edmcman** [mahaloz/DAILA#30]
I'm trying to install DAILA in Ghidra 11.0.1 on aarch64 Mac.  I'm able to start the DAILA backend, but I never get the DAILA context menu in the decompiler.

Here is the Console - Scripting output:
```
daila_plugin.py> Running...
INFO:libbs_vendored.jfx_bridge.bridge:serving! (jfx_bridge v1.0.0, Python 2.7.3)
INFO:libbs_vendored.jfx_bridge.bridge:Server launching in background - will continue to run after launch script finishes...
daila_plugin.py> Finished!
WARNING:libbs_vendored.jfx_bridge.bridge:Handling connection from ('127.0.0.1', 53225)
WARNING:libbs_vendored.jfx_bridge.bridge:Closing connection from ('127.0.0.1', 53225)
```

I am guessing the "Closing connection" message is a bad sign.

Running `daila -s ghidra`, I get:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/daila", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dailalib/__main__.py", line 41, in main
    create_plugin(force_decompiler="ghidra")
  File "/opt/homebrew/lib/python3.11/site-packages/dailalib/__init__.py", line 36, in create_plugin
    deci = DecompilerInterface.discover(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/libbs/api/decompiler_interface.py", line 673, in discover
    return deci_class(**interface_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/interface.py", line 57, in __init__
    super().__init__(name="ghidra", artifact_lifter=GhidraArtifactLifter(self), supports_undo=True, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/libbs/api/decompiler_interface.py", line 100, in __init__
    self._init_gui_components(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/libbs/api/decompiler_interface.py", line 134, in _init_gui_components
    self.gui_register_ctx_menu(name, action_string, callback_func, category=category)
  File "/opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/interface.py", line 136, in gui_register_ctx_menu
    ctx_menu_action = create_context_action(self.ghidra, name, action_string, callback_func, category or "LibBS")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/hooks.py", line 9, in create_context_action
    ProgramLocationContextAction = ghidra.import_module_object("ghidra.app.context", "ProgramLocationContextAction")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'import_module_object'
```

Not quite sure why `self.ghidra` is None.

**Comment by mahaloz** [comment]
Ok, now that this bug has appeared on Mac, I'll take a look. This issue is linked to #27, which I had thought was only a Windows issue. The fact that `self.ghidra` is None likely means something crashed on the server-side, but it still connected.

**Comment by edmcman** [comment]
It looks like [this call](https://github.com/binsync/libbs/blob/main/libbs/decompilers/ghidra/interface.py#L57) adds the context menu, but ghidra isn't connected at that point.

If I move that base constructor call after the connection, then the context menu appears.

I get an exception, but I can't immediately tell if it's because that is a bogus fix or not:
```
Exception in thread Thread-5 (query_model):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/dailalib/api/ai_api.py", line 102, in _requires_function
    return f(*args, function=function, dec_text=dec_text, use_dec=use_dec, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/varbert/api.py", line 105, in query_model
    old_to_new_vars, renamed_code = self.predict_variable_names(function=function, decompilation_text=dec_text, use_decompiler=use_dec)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/varbert/api.py", line 67, in predict_variable_names
    preprocessor = DecompilationTextProcessor(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/varbert/text_processor.py", line 30, in __init__
    self._preprocess_code()
  File "/opt/homebrew/lib/python3.11/site-packages/varbert/text_processor.py", line 74, in _preprocess_code
    self._process_code_with_decompiler()
  File "/opt/homebrew/lib/python3.11/site-packages/varbert/text_processor.py", line 84, in _process_code_with_decompiler
    self._func.dec_obj = self._decompiler.get_decompilation_object(self._func)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/interface.py", line 205, in get_decompilation_object
    return self._ghidra_decompile(self._get_nearest_function(function.addr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/interface.py", line 672, in _ghidra_decompile
    dec_results = dec_interface.decompileFunction(func, 0, consle_monitor_cls())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jfx_bridge/bridge.py", line 2104, in __call__
    return self._bridge_conn.remote_call(self._bridge_handle, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jfx_bridge/bridge.py", line 194, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jfx_bridge/bridge.py", line 1064, in remote_call
    return self.deserialize_from_dict(self.send_cmd(command_dict))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jfx_bridge/bridge.py", line 903, in deserialize_from_dict
    raise BridgeException(
jfx_bridge.bridge.BridgeException: ('Cannot invoke "ghidra.program.model.pcode.Decoder.clear()" because "decoder" is null', <_bridged_java.lang.NullPointerException('java.lang.NullPointerException: Cannot invoke "ghidra.program.model.pcode.Decoder.clear()" because "decoder" is null', type=java.lang.NullPointerException, handle=7aef20a8-e307-49e9-b1f9-f616523a5711)>)
```

**Comment by edmcman** [comment]
```
> /opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/interface.py(677)_ghidra_decompile()
-> dec_results = dec_interface.decompileFunction(func, 0, consle_monitor_cls())
(Pdb) bt
  /opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py(1002)_bootstrap()
-> self._bootstrap_inner()
  /opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py(1045)_bootstrap_inner()
-> self.run()
  /opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py(982)run()
-> self._target(*self._args, **self._kwargs)
  /opt/homebrew/lib/python3.11/site-packages/dailalib/api/ai_api.py(102)_requires_function()
-> return f(*args, function=function, dec_text=dec_text, use_dec=use_dec, **kwargs)
  /opt/homebrew/lib/python3.11/site-packages/varbert/api.py(105)query_model()
-> old_to_new_vars, renamed_code = self.predict_variable_names(function=function, decompilation_text=dec_text, use_decompiler=use_dec)
  /opt/homebrew/lib/python3.11/site-packages/varbert/api.py(67)predict_variable_names()
-> preprocessor = DecompilationTextProcessor(
  /opt/homebrew/lib/python3.11/site-packages/varbert/text_processor.py(30)__init__()
-> self._preprocess_code()
  /opt/homebrew/lib/python3.11/site-packages/varbert/text_processor.py(74)_preprocess_code()
-> self._process_code_with_decompiler()
  /opt/homebrew/lib/python3.11/site-packages/varbert/text_processor.py(84)_process_code_with_decompiler()
-> self._func.dec_obj = self._decompiler.get_decompilation_object(self._func)
  /opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/interface.py(205)get_decompilation_object()
-> return self._ghidra_decompile(self._get_nearest_function(function.addr))
> /opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/interface.py(677)_ghidra_decompile()
-> dec_results = dec_interface.decompileFunction(func, 0, consle_monitor_cls())

(Pdb) list
672  	        print("decompile")
673  	        print(func)
674  	        if func is None:
675  	            import pdb
676  	            pdb.set_trace()
677  ->	        dec_results = dec_interface.decompileFunction(func, 0, consle_monitor_cls())
678  	        print("woo")
679  	        return dec_results
680  	
681  	    def _get_gstack_var(self, func: "GhidraFunction", offset: int) -> Optional["LocalVariableDB"]:
682  	        """
(Pdb) up
> /opt/homebrew/lib/python3.11/site-packages/libbs/decompilers/ghidra/interface.py(205)get_decompilation_object()
-> return self._ghidra_decompile(self._get_nearest_function(function.addr))
(Pdb) p function.addr
14952
(Pdb) p function
<Function: void entry(args=2); @0x3a68 vars=7 len=0xbdc>
(Pdb) p self._get_nearest_function(function.addr)
None
```

The code is at 0x10003a68, not 0x3a68.

**Comment by edmcman** [comment]
Could be wrong, but I bet this is coming from here: https://github.com/binsync/libbs/blob/38977fc604d05ee9bd0d8d3cf1d6fc84511c766c/libbs/decompilers/ghidra/interface.py#L147

**Comment by mahaloz** [comment]
I think you are close, I'm also debugging right now, it should be a `lift` not a `lower`:
https://github.com/binsync/libbs/pull/33/files#r1498304021

**Comment by mahaloz** [comment]
All functions are abstracted to their `lifted` form when doing calls from the API. I think somewhere down the line I messed up and forgot to validate that al the API follows this rule.

**Comment by mahaloz** [comment]
@edmcman if you want a quick local fix for now while I explore why the bridge failed, delete this function: 
https://github.com/binsync/libbs/blob/38977fc604d05ee9bd0d8d3cf1d6fc84511c766c/libbs/decompilers/ghidra/interface.py#L186

Looks like that TODO was the killer, it should be using its super now.

**Comment by edmcman** [comment]
Thanks!

**Comment by mahaloz** [comment]
Lmk if the latest DAILA version is fixed for you @edmcman. Note that if you are doing a local editable install, make sure you update libbs.

**Comment by edmcman** [comment]
It works -- thanks!
