### ISSUE TITLE
VarBERT Context Menu Failing in Binja

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [mahaloz/DAILA#34]
```
[Default] Traceback (most recent call last):
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 136, in _address_action
[Default]     action(view_obj, addr)
[Default]   File "/Users/visual/Library/Application Support/Binary Ninja/python310/site-packages/dailalib/__init__.py", line 31, in <lambda>
[Default]     return lambda *args, **kwargs: var_api.query_model(*args, **kwargs, remove_bad_names=not predict_for_all_variables)
[Default]   File "/Users/visual/Library/Application Support/Binary Ninja/python310/site-packages/dailalib/api/ai_api.py", line 102, in _requires_function
[Default]     return f(*args, function=function, dec_text=dec_text, use_dec=use_dec, **kwargs)
[Default] TypeError: VariableRenamingAPI.query_model() got multiple values for argument 'function'
```

**Comment by mahaloz** [comment]
Looks like the bug happens here:
https://github.com/mahaloz/DAILA/blob/ad2b13fb0f87a75ef7ce79aaeb7c3b67591c9ccb/dailalib/__init__.py#L31

And it only manifests in Binja because Binja passes a bunch of values `*args` through which override the `**kwargs`. All the other decompilers only send 1 arg, so we need to handle this somewhere. Probably in another handler in `LibBS` :(. 

I'll see if I can fix it today.
