### ISSUE TITLE
KeyError: 'summarize'

### ISSUE THREAD

**Issue by FBLeee** [mahaloz/DAILA#37]
```
D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\plugins\daila_plugin.py: Traceback (most recent call last):
  File "D:/Tools/IDA/ZIP/IDA_Pro_v7.5_Portable/plugins/daila_plugin.py", line 66, in PLUGIN_ENTRY
    return create_plugin(*args, **kwargs)
  File "D:/Tools/IDA/ZIP/IDA_Pro_v7.5_Portable/plugins/daila_plugin.py", line 11, in create_plugin
    return _create_plugin(*args, **kwargs)
  File "D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\python38\lib\site-packages\dailalib\__init__.py", line 13, in create_plugin
    litellm_api = LiteLLMAIAPI(delay_init=True)
  File "D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\python38\lib\site-packages\dailalib\api\litellm\litellm_api.py", line 31, in __init__
    from .prompts import PROMPTS, DEFAULT_STYLE
  File "D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\python38\lib\site-packages\dailalib\api\litellm\prompts\__init__.py", line 44, in <module>
    PROMPTS = load_prompts()
  File "D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\python38\lib\site-packages\dailalib\api\litellm\prompts\__init__.py", line 17, in load_prompts
    template_texts["summarize"],
KeyError: 'summarize'
```

Please tell me how to solve this problem？

**Comment by mahaloz** [comment]
It looks like the files failed to install or be resolved correctly in Windows. I'll see if I can fix it in #38

**Comment by mahaloz** [comment]
Ok bad news, @FBLeee, the CI passed, which means its hard for me to reproduce. Any chance you can hop on the BinSync discord: https://discord.gg/Qxezk2ep. It can possibly be faster to debug there whats wrong with your setup.

**Comment by FBLeee** [comment]
> Alternatively, would you be able to list the files in `D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\python38\lib\site-packages\dailalib\api\litellm\prompts`, my feeling is the `.j2` files got dropped on install.
First of all, thank you very much for your reply. There is indeed no ```.j2``` file in folder ```D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\python38\lib\site-packages\dailalib\api\litellm\prompts``` and folder ```D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\python38\lib\site-packages\dailalib\api\litellm```

![image](https://github.com/mahaloz/DAILA/assets/50468890/32742b5b-ec21-4d76-9776-9c936b0050e5)

**Comment by FBLeee** [comment]
> Alternatively, would you be able to list the files in `D:\Tools\IDA\ZIP\IDA_Pro_v7.5_Portable\python38\lib\site-packages\dailalib\api\litellm\prompts`, my feeling is the `.j2` files got dropped on install.

After copying the ```.j2``` file from git, it can be run successfully. Thank you very much
