### ISSUE TITLE
Exception with the latest version (3.4.0)

### ISSUE THREAD

**Issue by packmad** [mahaloz/DAILA#45]
Windows 10 - IDA Pro: 8.3 
After updating (dailalib 3.4.0, libbs 1.17.0), I always get this error:

```
Traceback (most recent call last):
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\decompilers\ida\compat.py", line 1160, in activate
    self.action_function(bs_ctx, deci=self.deci)
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\dailalib\api\litellm\prompts\prompt.py", line 107, in query_model
    return _query_model(ai_api=self.ai_api, function=function, dec_text=dec_text, use_dec=use_dec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\dailalib\api\ai_api.py", line 98, in _requires_function
    function = ai_api._dec_interface.functions[ai_api._dec_interface.gui_active_context().func_addr]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\api\artifact_dict.py", line 83, in __getitem__
    art = self._artifact_getter(item)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\decompilers\ida\interface.py", line 259, in _get_function
    return compat.function(addr, headless=self.headless, decompiler_available=self.decompiler_available, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\decompilers\ida\compat.py", line 69, in _execute_write
    thunk()
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\decompilers\ida\compat.py", line 65, in thunk
    output[0] = f(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\decompilers\ida\compat.py", line 103, in _requires_decompilation
    kwargs['ida_code_view'] = acquire_pseudocode_vdui(addr) if has_ui else DummyIDACodeView(addr)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\decompilers\ida\compat.py", line 69, in _execute_write
    thunk()
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\decompilers\ida\compat.py", line 65, in thunk
    output[0] = f(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\simo\AppData\Local\Programs\Python\Python311\Lib\site-packages\libbs\decompilers\ida\compat.py", line 964, in acquire_pseudocode_vdui
    func = ida_funcs.get_func(addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simo\IDA Pro 8.3\python\3\ida_funcs.py", line 746, in get_func
    return _ida_funcs.get_func(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'get_func', argument 1 of type 'ea_t'
```

**Comment by packmad** [comment]
Tested and working after your fix, thanks!
