### ISSUE TITLE
full installation error

### ISSUE THREAD

**Issue by QiuJYWX** [mahaloz/DAILA#52]
Hi @mahaloz,

I am installing DAILA with python3.10 and meeting the following error:  
Traceback (most recent call last):
  File "/home/qiu/anaconda3/bin/daila", line 5, in <module>
    from dailalib.__main__ import main
  File "/home/qiu/anaconda3/lib/python3.9/site-packages/dailalib/__init__.py", line 3, in <module>
    from .api import AIAPI, LiteLLMAIAPI
  File "/home/qiu/anaconda3/lib/python3.9/site-packages/dailalib/api/__init__.py", line 1, in <module>
    from .ai_api import AIAPI
  File "/home/qiu/anaconda3/lib/python3.9/site-packages/dailalib/api/ai_api.py", line 5, in <module>
    from libbs.api import DecompilerInterface
  File "/home/qiu/anaconda3/lib/python3.9/site-packages/libbs/api/__init__.py", line 2, in <module>
    from .decompiler_interface import DecompilerInterface
  File "/home/qiu/anaconda3/lib/python3.9/site-packages/libbs/api/decompiler_interface.py", line 40, in <module>
    class DecompilerInterface:
  File "/home/qiu/anaconda3/lib/python3.9/site-packages/libbs/api/decompiler_interface.py", line 803, in DecompilerInterface
    def _find_ghidra_type_name_in_types(self, type_name: str) -> Struct | Enum | Typedef | None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Would u plz help me figure out the root cause?

**Comment by mahaloz** [comment]
Hey @QiuJYWX, it looks like you are installing it with `3.9`:

> /home/qiu/anaconda3/lib/python3.9/site-packages/dailalib/init.py

You need 3.10. However, I am also annoyed how often this is coming up so I may just rollback the 3.10 specific changes.
