### ISSUE TITLE
AttributeError: 'javapackage' object has no attribute 'FunctionChangeRecord'

### ISSUE THREAD

**Issue by smnhff** [mahaloz/DAILA#58]
Hello,
I am trying to run daila in ghidra. I enabled the script, the ran `Tools>DAILA>Start DAILA Backend`. There is no entry in the context menu, and after a few seconds, the plugin seems to crash. 
```
daila_plugin.py> Running...
INFO:libbs_vendored.jfx_bridge.bridge:serving! (jfx_bridge v1.0.0, Python 2.7.3)
INFO:libbs_vendored.jfx_bridge.bridge:Server launching in background - will continue to run after launch script finishes...
[+] Starting the backend now...
daila_plugin.py> Finished!
WARNING:libbs_vendored.jfx_bridge.bridge:Handling connection from ('127.0.0.1', 42804)
WARNING:libbs_vendored.jfx_bridge.bridge:Closing connection from ('127.0.0.1', 42804)
WARNING:libbs_vendored.jfx_bridge.bridge:Handling connection from ('127.0.0.1', 35770)
Traceback (most recent call last):
  File "/home/user/ghidra_scripts/libbs_vendored/jfx_bridge/bridge.py", line 1004, in local_get
    result = getattr(target, name)
AttributeError: 'javapackage' object has no attribute 'FunctionChangeRecord'
WARNING:libbs_vendored.jfx_bridge.bridge:Closing connection from ('127.0.0.1', 35770)
ERROR:libbs_vendored.jfx_bridge.bridge:InteractiveListener failed trying to callback client: [Errno 9] Bad file descriptor
```

Running it from the command line gives a similar error:
`python3 -m dailalib -s ghidra`

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/jfx_bridge/bridge.py", line 1960, in __getattribute__
    result = self._bridged_get(attr)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/jfx_bridge/bridge.py", line 1981, in _bridged_get
    return self._bridge_conn.remote_get(self._bridge_handle, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/jfx_bridge/bridge.py", line 194, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/jfx_bridge/bridge.py", line 993, in remote_get
    return self.deserialize_from_dict(self.send_cmd(command_dict))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/jfx_bridge/bridge.py", line 903, in deserialize_from_dict
    raise BridgeException(
jfx_bridge.bridge.BridgeException: ("'javapackage' object has no attribute 'FunctionChangeRecord'", <_bridged_exceptions.AttributeError('AttributeError("'javapackage' object has no attribute 'FunctionChangeRecord'",)', type=exceptions.AttributeError, handle=5f65484b-ddd7-4f1d-a0af-46ddeec9744d)>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/.local/lib/python3.12/site-packages/dailalib/__main__.py", line 45, in <module>
    main()
  File "/home/user/.local/lib/python3.12/site-packages/dailalib/__main__.py", line 41, in main
    create_plugin(force_decompiler="ghidra")
  File "/home/user/.local/lib/python3.12/site-packages/dailalib/__init__.py", line 51, in create_plugin
    deci = DecompilerInterface.discover(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/libbs/api/decompiler_interface.py", line 956, in discover
    return deci_class(**interface_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/libbs/decompilers/ghidra/interface.py", line 62, in __init__
    super().__init__(
  File "/home/user/.local/lib/python3.12/site-packages/libbs/api/decompiler_interface.py", line 112, in __init__
    self._init_gui_components(*args, **kwargs)
  File "/home/user/.local/lib/python3.12/site-packages/libbs/decompilers/ghidra/interface.py", line 87, in _init_gui_components
    super()._init_gui_components(*args, **kwargs)
  File "/home/user/.local/lib/python3.12/site-packages/libbs/api/decompiler_interface.py", line 149, in _init_gui_components
    self.gui_register_ctx_menu(name, action_string, callback_func, category=category)
  File "/home/user/.local/lib/python3.12/site-packages/libbs/decompilers/ghidra/interface.py", line 178, in gui_register_ctx_menu
    ctx_menu_action = create_context_action(name, action_string, callback_func_wrap, category or "LibBS")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/libbs/decompilers/ghidra/hooks.py", line 207, in create_context_action
    from .compat.imports import ProgramLocationContextAction, MenuData
  File "/home/user/.local/lib/python3.12/site-packages/libbs/decompilers/ghidra/compat/imports.py", line 59, in <module>
    ChangeManager, ProgramChangeRecord, FunctionChangeRecord = import_objs("ghidra.program.util", ("ChangeManager", "ProgramChangeRecord", "FunctionChangeRecord"))
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/libbs/decompilers/ghidra/compat/imports.py", line 21, in import_objs
    new_objs = [getattr(module, obj) for obj in objs]
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/jfx_bridge/bridge.py", line 1964, in __getattribute__
    raise AttributeError(be.args[0])
AttributeError: 'javapackage' object has no attribute 'FunctionChangeRecord'
Exception ignored in: <function GhidraDecompilerInterface.__del__ at 0x786bf5cb9760>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/libbs/decompilers/ghidra/interface.py", line 71, in __del__
  File "/home/user/.local/lib/python3.12/site-packages/libbs/decompilers/ghidra/interface.py", line 116, in shutdown
  File "/home/user/.local/lib/python3.12/site-packages/libbs/api/decompiler_interface.py", line 155, in shutdown
  File "/home/user/.local/lib/python3.12/site-packages/libbs/configuration.py", line 46, in save
NameError: name 'open' is not defined
```

I am running Ghidra 11.0.3, I tried with Java 17.0.12 and 21.0.4.
DAILA is running `dailalib==3.8.0`

Any idea what I may be doing wrong?

**Comment by mahaloz** [comment]
Hi @smnhff, hmmmm I'm not sure. My best guess is that this is somehow related to 3.12? Have you tried on Python 3.10?

**Comment by InfiniteC0re** [comment]
@smnhff check if it works on a newer version of Ghidra. I have similar issue in Ghidra 11.0.1 with binsync but no issues when in Ghidra 11.1.2

**Comment by smnhff** [comment]
The upgrade to Ghidra 11.1.2 did indeed fix the issue, thank you both very much!
