### ISSUE TITLE
ModuleNotFoundError: No module named 'varbert' when installing

### ISSUE THREAD

**Issue by nuklea** [mahaloz/DAILA#67]
> pip freeze | grep -i daila
dailalib==3.13.1

> pip3 install dailalib && daila --install
Install for IDA Pro? [y/n]
y
Plugins Path [default = None] (enter nothing to use default):

[+] Installed ida to ...

Install for Binary Ninja? [y/n]
n
[!] Skipping or failed install for binja...

Creating Ghidra Scripts directory at C:\Users\nuklea\ghidra_scripts...
Install for Ghidra? [y/n]
n
[!] Skipping or failed install for ghidra...

Install for angr-management? [y/n]
n
[!] Skipping or failed install for angr...

[+] Plugin install completed! If anything was skipped by mistake, please manually install it.

We will now download local models for each decompiler you've installed. Ctrl+C to cancel.
Installing VarBERT models...
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\nuklea\.idapro\venv\Scripts\daila.exe\__main__.py", line 7, in <module>
  File "C:\Users\nuklea\.idapro\venv\lib\site-packages\dailalib\__main__.py", line 35, in main
    DAILAInstaller().install()
  File "C:\Users\nuklea\.idapro\venv\lib\site-packages\libbs\plugin_installer.py", line 79, in install
    self.display_epilogue()
  File "C:\Users\nuklea\.idapro\venv\lib\site-packages\dailalib\installer.py", line 70, in display_epilogue
    self.install_local_models()
  File "C:\Users\nuklea\.idapro\venv\lib\site-packages\dailalib\installer.py", line 74, in install_local_models
    self.install_varmodel_models()
  File "C:\Users\nuklea\.idapro\venv\lib\site-packages\dailalib\installer.py", line 78, in install_varmodel_models
    from varbert import install_model as install_varbert_model
ModuleNotFoundError: No module named 'varbert'

But I didnt installed 'dailalib[full]'

**Comment by mahaloz** [comment]
Good catch. This should be fixed in #68 , and available on `3.13.3`. In about 5 minutes, reinstall with:
```
pip install -U dailalib
```
