### ISSUE TITLE
DAILA plugin in IDA dependency issue

### ISSUE THREAD

**Issue by pc9441** [mahaloz/DAILA#72]
I am having issues trying to run DAILA under IDA Pro.
I have installed the plug-in under ~/.idapro/plugins, and IDA is not able to load dependencies for it:

> /Users/user/.idapro/plugins/daila_plugin.py: Traceback (most recent call last):
>   File "/Users/user/.idapro/plugins/daila_plugin.py", line 73, in PLUGIN_ENTRY
>     return create_plugin(*args, **kwargs)
>   File "/Users/user/.idapro/plugins/daila_plugin.py", line 10, in create_plugin
>     from dailalib import create_plugin as _create_plugin
> ModuleNotFoundError: No module named 'dailalib'

**Comment by mahaloz** [comment]
Hi @pc9441 do `pip install dailalib` to the same Python that your IDA Pro is using. If you are unsure which one that is, you can go in the `IDA Pro` folder that the binary is contained and execute `idapyswitch` to switch it to one you know has `dailalib` installed.

**Comment by pc9441** [comment]
Now I get this why I can't seem to have IDA connected to my Python.
It looks like IDA is running under Rosetta, and can't execute native Mac Python interpreter:

Cannot determine python library version for "/Users/user/.asdf/installs/python/3.12.7/bin/python": File is not for the correct architecture, expected x86_64

**Comment by pc9441** [comment]
I figured out that the only compatible Python is the default XCode provided Python installation that is built as universal binary (mixed ARM/X86 code). The issue is that it's Python 3.9, so that won't be compatible with the supplied libbs

>   File "/Users/user/Library/Python/3.9/lib/python/site-packages/libbs/api/decompiler_interface.py", line 817, in DecompilerInterface
>     def _find_ghidra_type_name_in_types(self, type_name: str) -> Struct | Enum | Typedef | None:
> TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by mahaloz** [comment]
I see, I'm not sure I can fix this one than
